#!/usr/bin/env bash
#install haproxy as load balancer and configure it to direct traffic

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 14231-web-01 44.200.178.214:80 check\n\tserver 14231-web-02 35.174.60.115:80 check" >> /etc/haproxy/haproxy.cfg 
sudo service haproxy restart
